[project]
name = "simple-summary"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.0",
    "openai>=2.21.0",
    "python-dotenv>=1.2.1",
    "uvicorn>=0.34.0",
]
